[package]
name = "playground"
version.workspace = true
edition.workspace = true

[[bin]]
name = "playground"
path = "src/main.rs"

[dependencies]
gpui = { workspace = true }
rediff = { workspace = true }
